### PR TITLE
Improve UI

### PR DESCRIPTION
**Pull request by MattiSG**
- Output number of blocked domains.
- Support `off` alias with double dash prefix.
- Remove date warning on macOS.
- Decrease amount of information displayed when checking for updates.
- Unify punctuation.
- Simplify code logic.

### CODE REVIEW

**Comment by MattiSG** [comment]
@odtvince since this slightly touches the disjunction logic you had added to support the GNU version of `date`, would you be able to try this PR on your setup? 😃

**Comment by bamthomas** [comment]
tested on ubuntu 16.04 install ok.

**Comment by MattiSG** [comment]
Thanks for your time @bamthomas! ❤️

Just to be 100% sure that I'm not misunderstanding “install ok”: you've tested on an Ubuntu 16.04 and it worked all right, you haven't just tried to install the script but actually downloaded the blocklist, is that correct? 😃

**Comment by bamthomas** [comment]
yes, I downloaded the script, and called it with `sudo adblock on`. Then it downloaded the url blacklist that I've seen added in the `/etc/hosts` on 0.0.0.0.

**Comment by MattiSG** [comment]
Thanks @bamthomas! 🙂

**Pull request merged**
